x = int(input('Digite um número inteiro: '))
print('-' * 12)
print('{} * {} = {}'.format(x, 1, x*1))
print('{} * {} = {}'.format(x, 2, x*2))
print('{} * {} = {}'.format(x, 3, x*3))
print('{} * {} = {}'.format(x, 4, x*4))
print('{} * {} = {}'.format(x, 5, x*5))
print('{} * {} = {}'.format(x, 6, x*6))
print('{} * {} = {}'.format(x, 7, x*7))
print('{} * {} = {}'.format(x, 8, x*8))
print('{} * {} = {}'.format(x, 9, x*9))
print('{} * {} = {}'.format(x, 10, x*10))
print('-' * 12)

